export const SITE_NAME = "Exclusive Foto Studio";

/** Fallback contact info, used until Supabase settings are configured. */
export const FALLBACK_SETTINGS = {
  phone: "+373 60 000 000",
  email: "hello@exclusivefotostudio.md",
  address: "Chișinău, Moldova",
  instagram_url: "https://instagram.com",
  facebook_url: "https://facebook.com",
  tiktok_url: null as string | null,
  whatsapp_url: null as string | null,
  hero_video_url: null as string | null,
  hero_image_url: null as string | null,
  hero_image_public_id: null as string | null,
  hero_title: null as string | null,
  hero_subtitle: null as string | null,
  hero_cta_text: null as string | null,
  hero_cta_href: null as string | null,
  hero_title_ro: null as string | null,
  hero_title_en: null as string | null,
  hero_subtitle_ro: null as string | null,
  hero_subtitle_en: null as string | null,
  hero_cta_text_ro: null as string | null,
  hero_cta_text_en: null as string | null,
  instant_printing_image_url: null as string | null,
  instant_printing_image_public_id: null as string | null,
  about_eyebrow: null as string | null,
  about_eyebrow_ro: null as string | null,
  about_eyebrow_en: null as string | null,
  about_title: null as string | null,
  about_title_ro: null as string | null,
  about_title_en: null as string | null,
  about_description: null as string | null,
  about_description_ro: null as string | null,
  about_description_en: null as string | null,
  about_stat_values: null as string[] | null,
  about_stat_values_ro: null as string[] | null,
  about_stat_values_en: null as string[] | null,
  about_stat_labels: null as string[] | null,
  about_stat_labels_ro: null as string[] | null,
  about_stat_labels_en: null as string[] | null,
  about_cta: null as string | null,
  about_cta_ro: null as string | null,
  about_cta_en: null as string | null,
  instant_printing_badge: null as string | null,
  instant_printing_badge_ro: null as string | null,
  instant_printing_badge_en: null as string | null,
  instant_printing_eyebrow: null as string | null,
  instant_printing_eyebrow_ro: null as string | null,
  instant_printing_eyebrow_en: null as string | null,
  instant_printing_title: null as string | null,
  instant_printing_title_ro: null as string | null,
  instant_printing_title_en: null as string | null,
  instant_printing_description: null as string | null,
  instant_printing_description_ro: null as string | null,
  instant_printing_description_en: null as string | null,
  instant_printing_points: null as string[] | null,
  instant_printing_points_ro: null as string[] | null,
  instant_printing_points_en: null as string[] | null,
  instant_printing_cta: null as string | null,
  instant_printing_cta_ro: null as string | null,
  instant_printing_cta_en: null as string | null,
  winter_eyebrow: null as string | null,
  winter_eyebrow_ro: null as string | null,
  winter_eyebrow_en: null as string | null,
  winter_title: null as string | null,
  winter_title_ro: null as string | null,
  winter_title_en: null as string | null,
  winter_description: null as string | null,
  winter_description_ro: null as string | null,
  winter_description_en: null as string | null,
  winter_cta: null as string | null,
  winter_cta_ro: null as string | null,
  winter_cta_en: null as string | null,
  featured_eyebrow: null as string | null,
  featured_eyebrow_ro: null as string | null,
  featured_eyebrow_en: null as string | null,
  featured_title: null as string | null,
  featured_title_ro: null as string | null,
  featured_title_en: null as string | null,
  featured_subtitle: null as string | null,
  featured_subtitle_ro: null as string | null,
  featured_subtitle_en: null as string | null,
  featured_view_all: null as string | null,
  featured_view_all_ro: null as string | null,
  featured_view_all_en: null as string | null,
  contact_cta_eyebrow: null as string | null,
  contact_cta_eyebrow_ro: null as string | null,
  contact_cta_eyebrow_en: null as string | null,
  contact_cta_title: null as string | null,
  contact_cta_title_ro: null as string | null,
  contact_cta_title_en: null as string | null,
  contact_cta_subtitle: null as string | null,
  contact_cta_subtitle_ro: null as string | null,
  contact_cta_subtitle_en: null as string | null,
  contact_cta_button: null as string | null,
  contact_cta_button_ro: null as string | null,
  contact_cta_button_en: null as string | null,
  footer_tagline: null as string | null,
  footer_tagline_ro: null as string | null,
  footer_tagline_en: null as string | null,
  contact_page_eyebrow: null as string | null,
  contact_page_eyebrow_ro: null as string | null,
  contact_page_eyebrow_en: null as string | null,
  contact_page_title: null as string | null,
  contact_page_title_ro: null as string | null,
  contact_page_title_en: null as string | null,
  contact_page_subtitle: null as string | null,
  contact_page_subtitle_ro: null as string | null,
  contact_page_subtitle_en: null as string | null,
  show_services: true,
  show_instant_printing: true,
  show_winter_locations: true,
  show_featured_projects: true,
  show_pricing: true,
};

